[package]
name = "confgen"
version = "0.1.0"
edition = "2021"
[dependencies]
ansi_term = "0.12.1"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
lazy_static = "1.4.0"